const KEYS_LIST_COMMAND = 'KEYS';
const MEMBERS_LIST_COMMAND = 'MEMBERS';
const ADD_KEYS_COMMAND = 'ADD';
const ITEMS_LIST_COMMAND = 'ITEMS';
const REMOVE_COMMAND = 'REMOVE';
const REMOVE_ALL_COMMAND = 'REMOVEALL';
const KEY_EXISTS_COMMAND = 'KEYEXISTS';
const MEMBER_EXISTS_COMMAND = 'MEMBEREXISTS';
const ALL_MEMBERS_COMMAND = 'ALLMEMBERS';
const CLEAR_COMMAND = 'CLEAR';
const QUIT_COMMAND = 'QUIT';
const KEYS_COUNT_COMMAND = 'KEYSCOUNT';
const MEMBERS_COUNT_COMMAND = 'MEMBERSCOUNT';

module.exports = {
    KEYS_LIST_COMMAND,
    MEMBERS_LIST_COMMAND,
    ADD_KEYS_COMMAND,
    ITEMS_LIST_COMMAND,
    REMOVE_COMMAND,
    REMOVE_ALL_COMMAND,
    KEY_EXISTS_COMMAND,
    MEMBER_EXISTS_COMMAND,
    ALL_MEMBERS_COMMAND,
    CLEAR_COMMAND,
    QUIT_COMMAND,
    KEYS_COUNT_COMMAND,
    MEMBERS_COUNT_COMMAND
}