const INFORMATION = `Please enter any of the below commands. 
    ADD, ITEMS, KEYS, MEMBERS, ALLMEMBERS, REMOVE, REMOVEALL,
    KEYEXISTS, MEMBEREXISTS, KEYSCOUNT, MEMBERSCOUNT, CLEAR, QUIT`;

module.exports = {
    INFORMATION
}